### PR TITLE
Improve kdf::derive_key type-safety

### PR DESCRIPTION
**Pull request by iazel**
When we want to derive a new key with `hash::kdf::derive_key` we need to pass context as a `&str`, however it has a strict requirement on length that is checked at runtime.

We can move this error at compile-time by changing the type to `&[u8; CONTEXT_SIZE]`. Using this type in rust is quite convenient, instead of `"UserName"` we now have `b"UserName"`.

Another requirement is that context must not contain any null byte `0x00`, however passing a string such as `"UserNam\0"` before would panic. We now surface this error to the user, which is less surprising as a behaviour.

I understand that this is a breaking change for a relatively small improvement, but given the lib is at 0.1.0, I hope it's still fine to add :)

### CODE REVIEW

**Comment by tom25519** [comment]
Hey, thank you for this! This makes a lot of sense, I'm not certain why I didn't take this approach before :sweat_smile: 

The panic should definitely be thought of as a bug, and I can think of a couple of other places in the codebase where it's also present, so I'll need to take a look through and get those corrected also.

Would you be able to fix the current failing tests by updating the usage of `kdf::derive_key` within the documentation strings? I'll get this merged after that.

Thank you again!

**Comment by iazel** [comment]
No worries, considering all that you did, it is normal to miss a thing or two ;) 

Tests fixed, I'm still not used to the docs one! I've amended the commit, now it should be ready to be merged once the pipeline runs again.

**Comment by tom25519** [comment]
Perfect, thank you so much! I'll look into other string/CString conversion issues when I have some time over the next couple of days.

**Comment by tom25519** [comment]
This has now landed in version 0.2.0. Thank you again!

**Pull request merged**
